### ISSUE TITLE
Download progress info is wrong after a resume

### ISSUE THREAD

**Issue by jeffcunat** [castlabs/downstream_electron#20]
When we pause a download and then we resume it, the download progress percentage restarts from the beginning.
Is it the intended behavior ? I see in the download_stats.js file the comment 
// if for any reason the connection is broken or user stopped, then after resuming the available bytes are
//always bigger then the actual downloaded bytes.
Is it something we may fix to get more accurate values ?

**Comment by obecny** [comment]
@jeffcunat at the beginning I tried to reuse this information but unfortunately when download fail / player crashes etc. there can be many reasons for that the stats is no more reliable and if may happen something is missing and then resuming downloads might results in unexpected errors. That's why when you resume download it generates the needed links again, then doing a check if stored files can be "reused". So that's why it starts from 0. If there will be any problem detected to file during this check the file will be deleted and downloaded again. Usually this checks is pretty fast but it will make sure the final download is reliable and doesn't have any errors, no matter what happened during the download.

**Comment by jeffcunat** [comment]
@obecny  I totally agree with the fact to starts from 0 to avoid errors but after the check you mention for a resume, the downloadedParts calculation does not take into account the bandwidth (line 111 in downloaded_stats.js)
I have deeply analyzed the code and it seems that there is a missing piece of information in what is stored inside the downloaded.json file. The bandwidth is not stored (not present inside the api/manifest/json/link-save.js)
When adding the bandwidth field, the progress is a lot more accurate when resuming a download. I let you double check my analysis and I will propose a PR if you're ok with that.

**Comment by jeffcunat** [comment]
Fixed with PR #26
