### ISSUE TITLE
Detailed info on persistent storage/license.

### ISSUE THREAD

**Issue by fourscience** [castlabs/downstream_electron#25]
Hey guys!
So i noticed that you mention:
``` const persistent = require('./clpp_persistent.plugin.min'); ```
in your docs, linking to [Persistent](https://castlabs.github.io/downstream_electron/Persistent.html)

So what i would like to achieve is offline playback with Shaka with encrypted dash content, 
What i've got a short test stream, a license url and a license token to attach to each license request.
With shaka
``` player.getNetworkingEngine().registerRequestFilter ```
will run the code and i'm able to add the licenseToken header.

But for the "plugin" i'm stuck:
```
const persistentConfig = {
  licenseUrl: `https://manager.license/WidevineRightsManager.aspx`,
  serverCertificate: new Uint8Array([0]),
  licenseRequest: function (request) {  request.setRequestHeader("licenseRequestToken", token);
  },
  licenseResponse: function (request) {
    console.log("response", request.getAllResponseHeaders());
  }
};
```

At the moment, there is no request/response done and i'm kinda off by this topic.
The flow is:
- create the download
- call createPersistentSession
- call start
- when done give the offline url to shaka for playback, shaka should not call for the licenseUrl / intercept the request and return it the filesystem.

I hope you guys can give some hints to go with.

Thanks

**Comment by obecny** [comment]
@fourscience 
1. As stated in docs https://castlabs.github.io/downstream_electron/Persistent.html You have to implement an object which provides 2 methods -> createPersistentSession and removePersistentSession. This depends on drm server but you have to implement the whole logic about downloading license, parsing then creating a persistent session etc. The DOWNstream intself doesn't provide this. All it does is giving you the api to save persistent session id together with the movie so that then you can try to load it with the player which you have chosen and thats the 2nd point. As you need a place where you can somehow save the information about the persistent session id that's what DOWNstream does automatically as the function `createPersistentSession` should be a promise and resolved with the session id. This way it will be automatically added to all information about certain manifest and then return when you use api "info"
2. You need to have a player which basically supports loading the previously created persistent session. 
3. As last you need to have electron version which allows and supports to create an offline persistent session -> https://github.com/castlabs/electron-releases

**Comment by re-jim** [comment]
Are there any working examples of this implemented with real DRM systems?

**Comment by mackode** [comment]
I don't think there are public examples of this implemented. 
But there is proprietary castLabs player implementation working with DRMToday technology.
